// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptPDF(arg1) {
  return window['go']['main']['App']['DecryptPDF'](arg1);
}

export function EncryptPDF(arg1) {
  return window['go']['main']['App']['EncryptPDF'](arg1);
}
