name: Build and Publish
on: [push, pull_request]

jobs:
  build-wails:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {platform: linux/amd64, os: ubuntu-latest},
          {platform: darwin/universal, os: macos-latest},
          {platform: windows/amd64, os: windows-latest},
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Wails Build Action
        uses: dAppServer/wails-build-action@v2
        with:
          build-name: pdfcpu-gui
          build-platform: ${{ matrix.build.platform }}
