name: Build and Publish
on: [push, pull_request]

jobs:
  build-wails:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: pdfcpu-gui, os: ubuntu-latest, platform: linux/amd64},
          {name: pdfcpu-gui.app, os: macos-latest, platform: darwin/universal},
          {name: pdfcpu-gui.exe, os: windows-latest, platform: windows/amd64},
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Wails Build Action
        uses: dAppServer/wails-build-action@v2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
